Repository apache/openwhisk-release, pull requests merged in 2018-04, with the labels that each got.

#89 Clean up and refactor README contents with Rel. Mgr. tutorial.
  README.md
  docs/tutorial.md
Labels: review

#90 Add project repo. status table to README.
  README.md
Labels: review

#92 Update the Repo. status table with accurate links (e.g., Travis, LICENSE, NOTICE files)
  README.md
Labels: review

#114 Initial markdown to track project LICENSES, NOTICES and provide summary of notable references
  docs/project_licenses.md
Labels: documentation, review

#117 Update project_licenses.md to include tracking issues and latest PR updates
  docs/project_licenses.md
Labels: documentation, review

#124 Update repository status table to reflect latest Scancode support.
  README.md
Labels: documentation

#126 Update RAT pom.xml and document more excluded files in openwhisk repo
  docs/license_compliance.md
  tools/lib/pom.xml
Labels: review

#123 Update table with LICENSE PR and issue tracking.
  docs/project_licenses.md
Labels: documentation, review

#127 Add the spec to assemble the LICENSE file for each OpenWhisk repo
  docs/project_licenses.md
Labels: documentation, review

#128 Update README and license_compliance.md to be more accurate/informative
  README.md
  docs/license_compliance.md
  docs/project_licenses.md
Labels: review

#134 Update README to include disclaimer of status, as well as highlight s…
  README.md
  docs/project_licenses.md
Labels: review
