Repository apache/openwhisk-release, pull requests merged in 2018-06, with the labels that each got.

#173 Fix exclusions for wskdeploy repo.
  docs/license_exclusions.md
Labels: WIP

#181 Add openwhisk-kube-deploy to list of release repos.
  README.md
  docs/general_spec.md
  tools/config.json
Labels: next release

#183 Adjust docs to reflect addition of Kube deployment to release repos.
  docs/license_compliance.md
  docs/license_exclusions.md
Labels: documentation, review

#189 Add exclusions listing for incubator-openwhisk-deploy-kube repo.
  docs/license_exclusions.md
Labels: documentation, review
