Repository apache/openwhisk-release, pull requests merged in 2018-05, with the labels that each got.

#135 Add more exclusion files
  docs/license_compliance.md
  tools/lib/pom.xml
Labels: review

#136 Update LICENSE compliance tracking table to reflect latest PRs.
  docs/project_licenses.md
Labels: review

#143 Update tracking information and make this repo scancode compliant.
  NOTICE.md
  README.md
  docs/general_spec.md
  docs/pick_up_source_code.md
  docs/prerequisites.md
  docs/project_licenses.md
  docs/release_instructions.md
  docs/work_items.md
  tools/pgp_key_gen.conf
  tools/util.sh
Labels: documentation, review

#144 Update header scan policy document
  docs/license_compliance.md
  tools/lib/pom.xml
Labels: review

#145 Fix markdown files with a typo. in the Hash license header.
  NOTICE.md
  README.md
  docs/general_spec.md
  docs/generate_release_notes.md
  docs/license_compliance.md
  docs/package_artifacts.md
  docs/pick_up_source_code.md
  docs/prepare_release.md
  docs/prerequisites.md
  docs/project_licenses.md
  docs/publish_apache_directory.md
  docs/push_stage_url.md
  docs/release_instructions.md
  docs/sign_artifacts.md
  docs/upload_public_key.md
  docs/work_items.md
  tools/lib/release_template.md
Labels: apache, documentation

#150 Create detailed list of all ASF license exclusions by file.
  docs/license_compliance.md
  docs/release_instructions.md
Labels: apache

#154 Provide per-repo., file-level ASF license header exclusion listing.
  docs/license_compliance.md
  docs/license_exclusions.md
Labels: Legal, apache

#160 Clean up Openwhisk repo. ASF license header inclusion/exclusion tables
  docs/license_compliance.md
  docs/license_exclusions.md
Labels: apache, documentation, review

#162 clean up repos. and file exclusion listings.
  docs/license_compliance.md
  docs/license_exclusions.md
Labels: review

#164 Fix or document last remaining exclusions across all release repos.
  docs/license_compliance.md
  docs/license_exclusions.md
Labels: review
